# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Create a new notebook for your code-along:

From our submission directory, type:
    
    jupyter notebook

From the IPython Dashboard, open a new notebook.
Change the title to: "Numpy and Pandas"

# Introduction to Numpy

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [1]:
import numpy as np

### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [12]:
# Creating arrays
a = np.zeros((3)) # all 0s
b = np.ones((2,3)) # 2 x 3
c = np.random.randint(1,10,(2,3,4)) # random ints between [1,10]
d = np.arange(0,11,1) # include 0 but not include 11, layout at cadence of 1
print d

[ 0  1  2  3  4  5  6  7  8  9 10]


What are these functions?

    arange?

In [13]:
# Note the way each array is printed:
a,b,c,d

(array([ 0.,  0.,  0.]), array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]), array([[[6, 9, 1, 7],
         [3, 1, 8, 1],
         [6, 7, 6, 8]],
 
        [[5, 1, 5, 3],
         [2, 3, 1, 2],
         [2, 8, 7, 2]]]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [ ]:
## Arithmetic in arrays is element wise

In [15]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [16]:
c = a-b
c

array([20, 29, 38, 47])

In [17]:
b**2

array([0, 1, 4, 9])

## Indexing, Slicing and Iterating

In [18]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [19]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [20]:
a[2:5] # the index starts at 0, aka first element in the array is index 0; the indexcing / slicing works like [)

array([ 4,  9, 16])

In [ ]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [21]:
b = np.random.randint(1,100,(4,4))

In [22]:
b

array([[50, 20, 87, 69],
       [96, 42, 94,  1],
       [74, 80, 33, 58],
       [11, 35, 31, 64]])

In [23]:
# Guess the output
print(b[2,3])
print(b[0,0])


58
50


In [24]:
b[0:3,1],b[:,1] # ":" means give me everything

(array([20, 42, 80]), array([20, 42, 80, 35]))

In [25]:
b[1:3,:]

array([[96, 42, 94,  1],
       [74, 80, 33, 58]])

# Introduction to Pandas

* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt # plotting library for visualization

In [27]:
dates = pd.date_range('20140101',periods=6)
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [28]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

Index([u'A', u'B', u'C', u'D'], dtype='object')

In [31]:
# Index, columns, underlying numpy data
df.T
df

A         B         C         D
2014-01-01 -0.125400 -0.231586 -0.282987 -1.058610
2014-01-02 -0.053622 -1.385155  0.419987 -1.437697
2014-01-03  1.512163  0.090806 -1.490161 -0.583492
2014-01-04 -1.356425  0.287828 -1.343611  1.792990
2014-01-05  2.418174 -0.620300  0.215443  0.147641
2014-01-06 -0.712237 -0.248048  0.610557  1.165476

In [32]:
df2 = pd.DataFrame({ 'A' : 1.,
                     'B' : pd.Timestamp('20130102'),
                     'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                     'D' : np.array([3] * 4,dtype='int32'),
                     'E' : 'foo' })
    

df2

# columns with fewer number of obs will be pasted down to be full

A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo

In [33]:
# With specific dtypes
df2.dtypes

# check data type

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

#### Viewing Data

In [34]:
df.head()
# df.head(2) show only 2 obs

A         B         C         D
2014-01-01 -0.125400 -0.231586 -0.282987 -1.058610
2014-01-02 -0.053622 -1.385155  0.419987 -1.437697
2014-01-03  1.512163  0.090806 -1.490161 -0.583492
2014-01-04 -1.356425  0.287828 -1.343611  1.792990
2014-01-05  2.418174 -0.620300  0.215443  0.147641

In [35]:
df.tail()

A         B         C         D
2014-01-02 -0.053622 -1.385155  0.419987 -1.437697
2014-01-03  1.512163  0.090806 -1.490161 -0.583492
2014-01-04 -1.356425  0.287828 -1.343611  1.792990
2014-01-05  2.418174 -0.620300  0.215443  0.147641
2014-01-06 -0.712237 -0.248048  0.610557  1.165476

In [36]:
df.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [37]:
df.describe() # show summary statistics of all obs (count will exclude null values)

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.280442 -0.351076 -0.311795  0.004385
std    1.416198  0.595004  0.907550  1.274592
min   -1.356425 -1.385155 -1.490161 -1.437697
25%   -0.565528 -0.527237 -1.078455 -0.939831
50%   -0.089511 -0.239817 -0.033772 -0.217926
75%    1.120717  0.010208  0.368851  0.911017
max    2.418174  0.287828  0.610557  1.792990

In [38]:
df.sort_values(by='B') # sort values in col B and display it
# if sort_value(), then sort everyone in a single column

A         B         C         D
2014-01-02 -0.053622 -1.385155  0.419987 -1.437697
2014-01-05  2.418174 -0.620300  0.215443  0.147641
2014-01-06 -0.712237 -0.248048  0.610557  1.165476
2014-01-01 -0.125400 -0.231586 -0.282987 -1.058610
2014-01-03  1.512163  0.090806 -1.490161 -0.583492
2014-01-04 -1.356425  0.287828 -1.343611  1.792990

### Selection

In [39]:
df[['A','B']] # select A, B col
# when in single df['A'], it returns a series, which limits a lot of the functions you can run in python
# alternatively, use df[['A']]

A         B
2014-01-01 -0.125400 -0.231586
2014-01-02 -0.053622 -1.385155
2014-01-03  1.512163  0.090806
2014-01-04 -1.356425  0.287828
2014-01-05  2.418174 -0.620300
2014-01-06 -0.712237 -0.248048

In [40]:
df[0:3] # return first 3 rows and all columns

A         B         C         D
2014-01-01 -0.125400 -0.231586 -0.282987 -1.058610
2014-01-02 -0.053622 -1.385155  0.419987 -1.437697
2014-01-03  1.512163  0.090806 -1.490161 -0.583492

In [41]:
# By label
df.loc[dates[0]]

# give me row whose index location is 0
# for loc, both the start and the end are included

#.loc = locations

A   -0.125400
B   -0.231586
C   -0.282987
D   -1.058610
Name: 2014-01-01 00:00:00, dtype: float64

In [42]:
# multi-axis by label
df.loc[:,['A','B']]

A         B
2014-01-01 -0.125400 -0.231586
2014-01-02 -0.053622 -1.385155
2014-01-03  1.512163  0.090806
2014-01-04 -1.356425  0.287828
2014-01-05  2.418174 -0.620300
2014-01-06 -0.712237 -0.248048

In [43]:
# Date Range
df.loc['20140102':'20140104',['B']]

B
2014-01-02 -1.385155
2014-01-03  0.090806
2014-01-04  0.287828

In [44]:
# Fast access to scalar
df.at[dates[1],'B']

-1.3851548561187084

In [45]:
# iloc provides integer locations similar to np style (pretend numbering rows always from 0,1,2...)
# iloc with numbers
df.iloc[3:]

A         B         C         D
2014-01-04 -1.356425  0.287828 -1.343611  1.792990
2014-01-05  2.418174 -0.620300  0.215443  0.147641
2014-01-06 -0.712237 -0.248048  0.610557  1.165476

### Boolean Indexing

In [50]:
df[df.B < 0] # Basically a 'where' operation
# either df.A or df['A'] work to access the column
# df.{col_name without quotation marks} would select that column, like df$col_name in R
# df[(df.B>0) & (df.A<0)]

SyntaxError: invalid syntax (<ipython-input-50-625b29edf93b>, line 1)

### Setting

In [47]:
df_posA = df.copy() # Without "copy" it would act on the dataset

df_posA[df_posA.A < 0] = -1*df_posA # perform a transformation on selected data

In [48]:
df_posA

A         B         C         D
2014-01-01  0.125400  0.231586  0.282987  1.058610
2014-01-02  0.053622  1.385155 -0.419987  1.437697
2014-01-03  1.512163  0.090806 -1.490161 -0.583492
2014-01-04  1.356425 -0.287828  1.343611 -1.792990
2014-01-05  2.418174 -0.620300  0.215443  0.147641
2014-01-06  0.712237  0.248048 -0.610557 -1.165476

In [3]:
#Setting new column aligns data by index (a new series)
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [52]:
s1

2014-01-02    1
2014-01-03    2
2014-01-04    3
2014-01-05    4
2014-01-06    5
2014-01-07    6
Freq: D, dtype: int64

In [53]:
df['F'] = s1 # add the new column to an existing df by directly naming the column F

In [54]:
df

A         B         C         D    F
2014-01-01 -0.125400 -0.231586 -0.282987 -1.058610  NaN
2014-01-02 -0.053622 -1.385155  0.419987 -1.437697  1.0
2014-01-03  1.512163  0.090806 -1.490161 -0.583492  2.0
2014-01-04 -1.356425  0.287828 -1.343611  1.792990  3.0
2014-01-05  2.418174 -0.620300  0.215443  0.147641  4.0
2014-01-06 -0.712237 -0.248048  0.610557  1.165476  5.0

In [ ]:
# df['D']=df['D']-1 # revise/overwrite an existing column [C]

### Missing Data

In [58]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])
# documentation on "re-index":
# https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.reindex.html

A         B         C         D    F   E
2014-01-01 -0.125400 -0.231586 -0.282987 -1.058610  NaN NaN
2014-01-02 -0.053622 -1.385155  0.419987 -1.437697  1.0 NaN
2014-01-03  1.512163  0.090806 -1.490161 -0.583492  2.0 NaN
2014-01-04 -1.356425  0.287828 -1.343611  1.792990  3.0 NaN

In [56]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [57]:
df1

A         B         C         D    F    E
2014-01-01 -0.125400 -0.231586 -0.282987 -1.058610  NaN  1.0
2014-01-02 -0.053622 -1.385155  0.419987 -1.437697  1.0  1.0
2014-01-03  1.512163  0.090806 -1.490161 -0.583492  2.0  NaN
2014-01-04 -1.356425  0.287828 -1.343611  1.792990  3.0  NaN

In [5]:
# find where values are null
pd.isnull(df1)
pd.isnull(df1).sum() # the number of missing values for each column

NameError: name 'df1' is not defined

### Operations

In [4]:
df.describe()
df.count()

NameError: name 'df' is not defined

In [64]:
df.mean(),  # average each column
df.mean(1)  # average for each row

(A    0.280442
 B   -0.351076
 C   -0.311795
 D    0.004385
 F    3.000000
 dtype: float64, 2014-01-01   -0.424646
 2014-01-02   -0.291297
 2014-01-03    0.305863
 2014-01-04    0.476156
 2014-01-05    1.232192
 2014-01-06    1.163150
 Freq: D, dtype: float64)

### Applying functions

In [6]:
df

NameError: name 'df' is not defined

In [66]:
df.apply(np.cumsum)
# apply a function
# when applying on a df, it breaks out by column
# np.cumsum: calculate cumulative sum for each column

A         B         C         D     F
2014-01-01 -0.125400 -0.231586 -0.282987 -1.058610   NaN
2014-01-02 -0.179022 -1.616741  0.137000 -2.496307   1.0
2014-01-03  1.333141 -1.525936 -1.353161 -3.079799   3.0
2014-01-04 -0.023285 -1.238107 -2.696772 -1.286810   6.0
2014-01-05  2.394890 -1.858407 -2.481330 -1.139169  10.0
2014-01-06  1.682652 -2.106456 -1.870772  0.026307  15.0

In [67]:
df.apply(lambda x: x.max() - x.min())
# apply a custom function: subtracting the max value from the min

A    3.774600
B    1.672983
C    2.100718
D    3.230686
F    4.000000
dtype: float64

In [ ]:
def custom_func(x):
    return x.max()

df.apply(custom_func)
# specify the function first

In [70]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower() # transform all strings in to lowercase

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

### Merge

In [71]:
np.random.randn(10,4)

array([[ 0.27971395, -0.25810542, -0.73987777, -0.68637655],
       [ 1.78578628, -0.81099072, -1.14399281, -0.32299881],
       [-0.28971699,  1.46154127, -1.9881389 , -0.1825192 ],
       [ 0.44722637, -0.10231722, -0.63748839, -0.33488976],
       [-1.01569811,  0.34357395,  1.65288559,  0.4769241 ],
       [ 0.32922529,  0.41622712, -0.4034701 ,  2.80361608],
       [ 0.85469873,  1.05797929, -0.04000142,  0.64811215],
       [-0.48202483, -1.23340063,  0.90311364, -0.13332279],
       [ 1.68313125,  0.86666898,  0.76755753,  1.07773325],
       [-2.18608481,  0.0964431 ,  1.10800005, -1.349942  ]])

In [72]:
#Concatenating pandas objects together
df = pd.DataFrame(np.random.randn(10,4))
df

0         1         2         3
0 -1.508143 -0.596969  0.365857  0.302251
1 -1.213794 -0.182400 -0.200787  0.096354
2  0.915979 -1.143572  0.515625  1.661699
3 -0.286099  0.024995  0.110312 -0.320045
4  0.560732 -1.592271 -0.930730 -0.382164
5 -1.395884  1.873426  0.024851 -1.208374
6  1.282751  1.521171 -0.658172 -0.183301
7  0.120338 -0.796533  0.694693 -0.674943
8  0.363008  0.141466  0.512912 -0.142185
9  0.729498  0.480199 -0.108734  1.540478

In [73]:
# Break it into pieces
pieces = [df[:3], df[3:7],df[7:]]
pieces

[          0         1         2         3
 0 -1.508143 -0.596969  0.365857  0.302251
 1 -1.213794 -0.182400 -0.200787  0.096354
 2  0.915979 -1.143572  0.515625  1.661699,
           0         1         2         3
 3 -0.286099  0.024995  0.110312 -0.320045
 4  0.560732 -1.592271 -0.930730 -0.382164
 5 -1.395884  1.873426  0.024851 -1.208374
 6  1.282751  1.521171 -0.658172 -0.183301,
           0         1         2         3
 7  0.120338 -0.796533  0.694693 -0.674943
 8  0.363008  0.141466  0.512912 -0.142185
 9  0.729498  0.480199 -0.108734  1.540478]

In [74]:
pd.concat(pieces)

0         1         2         3
0 -1.508143 -0.596969  0.365857  0.302251
1 -1.213794 -0.182400 -0.200787  0.096354
2  0.915979 -1.143572  0.515625  1.661699
3 -0.286099  0.024995  0.110312 -0.320045
4  0.560732 -1.592271 -0.930730 -0.382164
5 -1.395884  1.873426  0.024851 -1.208374
6  1.282751  1.521171 -0.658172 -0.183301
7  0.120338 -0.796533  0.694693 -0.674943
8  0.363008  0.141466  0.512912 -0.142185
9  0.729498  0.480199 -0.108734  1.540478

In [75]:
# Also can "Join" and "Append"
df

0         1         2         3
0 -1.508143 -0.596969  0.365857  0.302251
1 -1.213794 -0.182400 -0.200787  0.096354
2  0.915979 -1.143572  0.515625  1.661699
3 -0.286099  0.024995  0.110312 -0.320045
4  0.560732 -1.592271 -0.930730 -0.382164
5 -1.395884  1.873426  0.024851 -1.208374
6  1.282751  1.521171 -0.658172 -0.183301
7  0.120338 -0.796533  0.694693 -0.674943
8  0.363008  0.141466  0.512912 -0.142185
9  0.729498  0.480199 -0.108734  1.540478

### Grouping


In [76]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [77]:
df

A      B         C         D
0  foo    one  0.670417 -2.230308
1  bar    one -0.015861  0.056774
2  foo    two  0.342490  0.575456
3  bar  three  1.342045  0.978275
4  foo    two -0.964326  1.720298
5  bar    two  0.101559  0.037028
6  foo    one  0.657440 -1.787005
7  foo  three  0.853471 -0.227550

In [78]:
df.groupby(['A','B']).sum()
# you can do mean, sd. etc

C         D
A   B                        
bar one   -0.015861  0.056774
    three  1.342045  0.978275
    two    0.101559  0.037028
foo one    1.327857 -4.017312
    three  0.853471 -0.227550
    two   -0.621836  2.295754

### Reshaping

In [ ]:
# You can also stack or unstack levels

In [79]:
a = df.groupby(['A','B']).sum()

In [80]:
# Pivot Tables
pd.pivot_table(df,values=['C','D'],index=['A'],columns=['B'])

C                             D                    
B         one     three       two       one     three       two
A                                                              
bar -0.015861  1.342045  0.101559  0.056774  0.978275  0.037028
foo  0.663929  0.853471 -0.310918 -2.008656 -0.227550  1.147877

### Time Series


In [81]:
import pandas as pd
import numpy as np

In [94]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [95]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [84]:
ts

2014-01-01 00:00:00    188
2014-01-01 00:00:01    393
2014-01-01 00:00:02    444
2014-01-01 00:00:03    270
2014-01-01 00:00:04    446
2014-01-01 00:00:05    459
2014-01-01 00:00:06     16
2014-01-01 00:00:07    395
2014-01-01 00:00:08     81
2014-01-01 00:00:09    314
2014-01-01 00:00:10    335
2014-01-01 00:00:11    356
2014-01-01 00:00:12    357
2014-01-01 00:00:13    307
2014-01-01 00:00:14    497
2014-01-01 00:00:15    100
2014-01-01 00:00:16    157
2014-01-01 00:00:17    263
2014-01-01 00:00:18    142
2014-01-01 00:00:19     42
2014-01-01 00:00:20    245
2014-01-01 00:00:21    470
2014-01-01 00:00:22    148
2014-01-01 00:00:23     74
2014-01-01 00:00:24    276
2014-01-01 00:00:25     49
2014-01-01 00:00:26    314
2014-01-01 00:00:27    340
2014-01-01 00:00:28    264
2014-01-01 00:00:29     58
                      ... 
2014-01-01 00:01:10    112
2014-01-01 00:01:11    165
2014-01-01 00:01:12    373
2014-01-01 00:01:13    471
2014-01-01 00:01:14    301
2014-01-01 00:01:15    180
2

In [96]:
# Built in resampling
ts.resample('1Min').mean() # Resample secondly to 1Minutely

2014-01-01 00:00:00    229.633333
2014-01-01 00:01:00    248.250000
Freq: T, dtype: float64

In [97]:
# Many additional time series features
ts. #use tab

SyntaxError: invalid syntax (<ipython-input-97-5c9240a56f62>, line 2)

### Plotting


In [93]:
ts.plot()

In [88]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [89]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [90]:
# Pandas plot function will print with labels as default

In [91]:
df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

#### The benefits of open source:

Let's look under x's in plt modules

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/10min.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas